//pins declarations
#define DMOTOR1 2
#define DMOTOR1D 3
#define DIRECTION1M1 39
#define DIRECTION2M1 43
#define PWM1 9
#define DMOTOR2 18
#define DMOTOR2D 19
#define DIRECTION1M2 51
#define DIRECTION2M2 53
#define PWM2 10
#define TRIGPIN1  11   //the first ultrasonic sensor placed on the front side of the robot
#define ECHOPIN1 12
#define TRIGPIN2  2   //the second ultrasonic sensor placed on the right of the robot
#define ECHOPIN2 3   

//defining constants
#define d_baseline 20  //the distance between the two wheels' centers
#define wheel_diameter 6 // the diameter of the wheel in centimeters
#define ticks_per_revolution 480 //the number of pulses generated by the encoder when it completes a full rotation